### ISSUE TITLE
NoScript update for Firefox on 28 Nov 2025 broke execution of JavaScript in local files

### ISSUE THREAD

**Issue by DrMicrobit** [hackademix/noscript#489]
Hi,
running Ubuntu 24.04, Firefox 145.0.2.

That Firefox has just three extensions on it:
- AdBlock Plus, updated 24 Nov
- Ghostery, updated 21 Nov
- NoScript, updated sometime today, 28 Nov

Sometime today, single-file HTML with embedded JavaScript stopped working when I loaded them from my filesystem with very funny JavaScript errors on the console.

The very same files, when loaded from any web server, works flawlessly.

Example: 
https://drmicrobit.github.io/lllm_suit/tests/03_SpaceInvaders_ddoc01/local/qwen3-coder-30B-unsloth/4bitUD_t1/space_invaders.html

Via the github repo, works flawlessly.

From local file, it works only if I disable NoScript. When I have NoScript enabled, I get this error message (removed exact path for brevity):
```text
Uncaught SyntaxError: redeclaration of let gameState
    <anonymous> file:///.../space_invaders.html:30
```

That very same file worked flawlessly from the local filesystem the past few weeks and also this morning. The error message is wrong in that way that the file in question definitely declares gameStae only once (easy check with grep).

This happens to *all* HTML/JavaScript files in that repository: from the web, they run. From local, silly error messages.

The only thing that I can trace to have changed today is NoScript, and indeed if I switch it off, everything works again.

Can you please look into this?

**Comment by hackademix** [comment]
Regression from 93833ad.

**Comment by hackademix** [comment]
Should be fixed in [latest development build](https://noscript.net/getit/#development-build), thanks.

**Comment by alex-kinokon** [comment]
The nscl submodule change is not pushed.

**Comment by hackademix** [comment]
> The nscl submodule change is not pushed.

Fixed, thanks.

**Comment by scorpi11** [comment]
I have 13.5.2 installed but file:/// URLs still have broken JavaScript.

I'm the user who opened issue #493 which was marked as a duplicate of this issue. I still see the same errors as mentioned in this issue.

According to the git log, this should be fixed in 13.5.2.

I already restarted Firefox and force-reloaded the website.

**Comment by DrMicrobit** [comment]
For what it's worth: for me, 13.5.2 put NoScript back into working state with local files, at least on OSX and for the example I posted above. I will check for Linux in the next couple of days, but would expect it to work there, too.
